[2022-11-22T12:20:28.669+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [queued]>
[2022-11-22T12:20:28.693+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [queued]>
[2022-11-22T12:20:28.693+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:20:28.693+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-22T12:20:28.694+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:20:28.728+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-22 12:20:26.951020+00:00
[2022-11-22T12:20:28.737+0000] {standard_task_runner.py:55} INFO - Started process 775 to run task
[2022-11-22T12:20:28.742+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_operator_v1', 'create_postgres_table', 'manual__2022-11-22T12:20:26.951020+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmp5klshdl1']
[2022-11-22T12:20:28.745+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_postgres_table
[2022-11-22T12:20:28.860+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [running]> on host 51961a9d5f51
[2022-11-22T12:20:29.025+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=JG13
AIRFLOW_CTX_DAG_ID=dag_postgres_operator_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T12:20:26.951020+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T12:20:26.951020+00:00
[2022-11-22T12:20:29.039+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-22T12:20:29.042+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host-gateway" to address: Temporary failure in name resolution

[2022-11-22T12:20:29.057+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221122T122026, start_date=20221122T122028, end_date=20221122T122029
[2022-11-22T12:20:29.079+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_postgres_table (could not translate host name "host-gateway" to address: Temporary failure in name resolution
; 775)
[2022-11-22T12:20:29.115+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-22T12:20:29.147+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
