[2022-11-16T14:55:05.077+0000] {processor.py:154} INFO - Started process (PID=403) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:05.078+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:55:05.079+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:05.079+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:05.083+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:05.081+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    scheduler=@daily
              ^
SyntaxError: invalid syntax
[2022-11-16T14:55:05.084+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:05.112+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T14:55:07.115+0000] {processor.py:154} INFO - Started process (PID=408) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:07.116+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:55:07.117+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:07.116+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:07.120+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:07.119+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    scheduler_interval=@daily
                       ^
SyntaxError: invalid syntax
[2022-11-16T14:55:07.121+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:07.156+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2022-11-16T14:55:37.338+0000] {processor.py:154} INFO - Started process (PID=432) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:37.339+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:55:37.340+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:37.340+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:37.342+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:37.341+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    scheduler_interval=@daily
                       ^
SyntaxError: invalid syntax
[2022-11-16T14:55:37.343+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:37.365+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2022-11-16T14:55:44.386+0000] {processor.py:154} INFO - Started process (PID=446) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:44.387+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:55:44.389+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:44.388+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:44.393+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:55:44.391+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:55:44.394+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:55:44.430+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2022-11-16T14:56:14.573+0000] {processor.py:154} INFO - Started process (PID=469) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:14.574+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:56:14.575+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:14.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:14.577+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:14.576+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:56:14.577+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:14.601+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2022-11-16T14:56:19.612+0000] {processor.py:154} INFO - Started process (PID=484) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:19.613+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:56:19.614+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:19.614+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:19.618+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:19.617+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:56:19.619+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:19.652+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2022-11-16T14:56:49.813+0000] {processor.py:154} INFO - Started process (PID=507) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:49.815+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:56:49.817+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:49.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:49.821+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:56:49.820+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:56:49.822+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:56:49.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.059 seconds
[2022-11-16T14:57:06.929+0000] {processor.py:154} INFO - Started process (PID=530) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:06.934+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:57:06.935+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:06.935+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:06.940+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:06.938+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:57:06.941+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:06.994+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.070 seconds
[2022-11-16T14:57:17.021+0000] {processor.py:154} INFO - Started process (PID=535) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:17.022+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:57:17.023+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:17.023+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:17.027+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:17.026+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:57:17.027+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:17.055+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2022-11-16T14:57:41.193+0000] {processor.py:154} INFO - Started process (PID=558) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:41.200+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:57:41.201+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:41.201+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:41.204+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:57:41.203+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2022-11-16T14:57:41.205+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:57:41.304+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.117 seconds
[2022-11-16T14:58:11.379+0000] {processor.py:154} INFO - Started process (PID=591) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:11.380+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:58:11.381+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:11.381+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:11.383+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:11.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2022-11-16T14:58:11.383+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:11.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2022-11-16T14:58:18.424+0000] {processor.py:154} INFO - Started process (PID=596) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:18.425+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:58:18.427+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:18.426+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:18.431+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:18.429+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:58:18.431+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:18.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2022-11-16T14:58:40.567+0000] {processor.py:154} INFO - Started process (PID=618) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:40.568+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:58:40.568+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:40.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:40.571+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:40.570+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:58:40.572+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:40.597+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2022-11-16T14:58:51.631+0000] {processor.py:154} INFO - Started process (PID=632) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:51.632+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:58:51.633+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:51.633+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:51.638+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:58:51.636+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:58:51.638+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:58:51.671+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2022-11-16T14:59:21.834+0000] {processor.py:154} INFO - Started process (PID=664) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:21.835+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:59:21.836+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:59:21.835+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:21.838+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:59:21.837+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T14:59:21.838+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:21.870+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2022-11-16T14:59:46.991+0000] {processor.py:154} INFO - Started process (PID=687) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:46.992+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T14:59:46.993+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:59:46.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:47.006+0000] {logging_mixin.py:137} INFO - [2022-11-16T14:59:47.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operators import bashOperator
ImportError: cannot import name 'bashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-11-16T14:59:47.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T14:59:47.064+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.078 seconds
[2022-11-16T15:00:17.186+0000] {processor.py:154} INFO - Started process (PID=709) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:17.190+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:00:17.191+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:17.191+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:17.197+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:17.195+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operators import bashOperator
ImportError: cannot import name 'bashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-11-16T15:00:17.197+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:17.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2022-11-16T15:00:28.288+0000] {processor.py:154} INFO - Started process (PID=722) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:28.289+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:00:28.291+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:28.290+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:28.297+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:28.293+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from airflow.operators import
                                 ^
SyntaxError: invalid syntax
[2022-11-16T15:00:28.298+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:28.350+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2022-11-16T15:00:58.463+0000] {processor.py:154} INFO - Started process (PID=753) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:58.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:00:58.466+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:58.466+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:58.470+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:00:58.468+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from airflow.operators import
                                 ^
SyntaxError: invalid syntax
[2022-11-16T15:00:58.471+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:00:58.519+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2022-11-16T15:01:23.653+0000] {processor.py:154} INFO - Started process (PID=775) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:23.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:01:23.655+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:01:23.655+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:23.658+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:01:23.657+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operator.bash_operator import bashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-16T15:01:23.659+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:23.680+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2022-11-16T15:01:39.774+0000] {processor.py:154} INFO - Started process (PID=790) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:39.775+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:01:39.776+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:01:39.776+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:39.779+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:01:39.778+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operator.bash_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-16T15:01:39.780+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:01:39.808+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2022-11-16T15:02:09.951+0000] {processor.py:154} INFO - Started process (PID=823) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:09.952+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:02:09.953+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:02:09.953+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:09.955+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:02:09.955+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operator.bash_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-16T15:02:09.956+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:09.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-11-16T15:02:40.161+0000] {processor.py:154} INFO - Started process (PID=846) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:40.162+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:02:40.163+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:02:40.163+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:40.167+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:02:40.166+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operator.bash_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-16T15:02:40.168+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:02:40.192+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2022-11-16T15:03:10.349+0000] {processor.py:154} INFO - Started process (PID=878) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:10.350+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:03:10.351+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:10.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:10.355+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:10.353+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operator.bash_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-16T15:03:10.355+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:10.378+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:03:32.508+0000] {processor.py:154} INFO - Started process (PID=902) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:32.523+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:03:32.524+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:32.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:32.549+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:32.546+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-11-16T15:03:32.549+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:32.589+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.087 seconds
[2022-11-16T15:03:50.607+0000] {processor.py:154} INFO - Started process (PID=915) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:50.608+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:03:50.609+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:50.609+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:50.622+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:03:50.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:03:50.622+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:03:50.650+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2022-11-16T15:04:10.703+0000] {processor.py:154} INFO - Started process (PID=938) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:10.705+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:04:10.706+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:10.706+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:10.715+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:10.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:04:10.717+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:10.747+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2022-11-16T15:04:27.867+0000] {processor.py:154} INFO - Started process (PID=951) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:27.874+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:04:27.875+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:27.875+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:27.896+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:27.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:04:27.896+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:27.952+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.089 seconds
[2022-11-16T15:04:52.002+0000] {processor.py:154} INFO - Started process (PID=973) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:52.004+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:04:52.005+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:52.005+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:52.018+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:04:52.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:04:52.020+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:04:52.071+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2022-11-16T15:05:04.049+0000] {processor.py:154} INFO - Started process (PID=987) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:04.050+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:05:04.051+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:04.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:04.058+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:04.057+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:05:04.059+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:04.083+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:05:10.101+0000] {processor.py:154} INFO - Started process (PID=1001) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:10.103+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:05:10.104+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:10.104+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:10.113+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:10.112+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:05:10.114+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:10.146+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2022-11-16T15:05:40.291+0000] {processor.py:154} INFO - Started process (PID=1024) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:40.292+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:05:40.292+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:40.292+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:40.298+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:05:40.297+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:05:40.298+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:05:40.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:06:10.462+0000] {processor.py:154} INFO - Started process (PID=1057) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:10.463+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:06:10.464+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:06:10.464+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:10.472+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:06:10.470+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:06:10.472+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:10.499+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2022-11-16T15:06:40.640+0000] {processor.py:154} INFO - Started process (PID=1082) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:40.640+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:06:40.641+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:06:40.641+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:40.648+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:06:40.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:06:40.648+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:06:40.671+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:07:10.839+0000] {processor.py:154} INFO - Started process (PID=1114) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:10.840+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:07:10.840+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:07:10.840+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:10.846+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:07:10.845+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:07:10.846+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:10.870+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2022-11-16T15:07:41.006+0000] {processor.py:154} INFO - Started process (PID=1136) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:41.007+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:07:41.008+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:07:41.008+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:41.014+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:07:41.014+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:07:41.015+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:07:41.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2022-11-16T15:08:11.202+0000] {processor.py:154} INFO - Started process (PID=1167) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:11.203+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:08:11.203+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:08:11.203+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:11.208+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:08:11.207+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:08:11.209+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:11.230+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2022-11-16T15:08:41.400+0000] {processor.py:154} INFO - Started process (PID=1190) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:41.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:08:41.401+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:08:41.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:41.409+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:08:41.408+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:08:41.409+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:08:41.433+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:09:11.604+0000] {processor.py:154} INFO - Started process (PID=1222) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:11.605+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:09:11.606+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:09:11.606+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:11.613+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:09:11.612+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:09:11.614+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:11.637+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:09:41.767+0000] {processor.py:154} INFO - Started process (PID=1246) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:41.767+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:09:41.768+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:09:41.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:41.775+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:09:41.774+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:09:41.776+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:09:41.797+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2022-11-16T15:10:11.991+0000] {processor.py:154} INFO - Started process (PID=1279) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:11.992+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:10:11.993+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:10:11.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:11.999+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:10:11.998+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:10:11.999+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:12.025+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:10:42.152+0000] {processor.py:154} INFO - Started process (PID=1312) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:42.153+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:10:42.153+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:10:42.153+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:42.159+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:10:42.159+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:10:42.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:10:42.183+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:11:12.346+0000] {processor.py:154} INFO - Started process (PID=1336) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:12.347+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:11:12.348+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:11:12.348+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:12.354+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:11:12.353+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:11:12.355+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:12.380+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2022-11-16T15:11:42.506+0000] {processor.py:154} INFO - Started process (PID=1368) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:42.507+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:11:42.508+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:11:42.507+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:42.514+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:11:42.513+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:11:42.514+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:11:42.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:12:12.722+0000] {processor.py:154} INFO - Started process (PID=1391) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:12.723+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:12:12.723+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:12:12.723+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:12.730+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:12:12.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:12:12.730+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:12.757+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2022-11-16T15:12:42.897+0000] {processor.py:154} INFO - Started process (PID=1424) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:42.898+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:12:42.898+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:12:42.898+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:42.904+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:12:42.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:12:42.905+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:12:42.931+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:13:13.086+0000] {processor.py:154} INFO - Started process (PID=1447) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:13.087+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:13:13.087+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:13:13.087+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:13.094+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:13:13.093+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:13:13.095+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:13.126+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2022-11-16T15:13:43.261+0000] {processor.py:154} INFO - Started process (PID=1479) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:43.261+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:13:43.262+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:13:43.262+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:43.267+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:13:43.266+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:13:43.268+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:13:43.290+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2022-11-16T15:14:13.467+0000] {processor.py:154} INFO - Started process (PID=1502) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:13.468+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:14:13.469+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:14:13.469+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:13.474+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:14:13.473+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:14:13.475+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:13.498+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-11-16T15:14:43.649+0000] {processor.py:154} INFO - Started process (PID=1534) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:43.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:14:43.650+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:14:43.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:43.658+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:14:43.657+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:14:43.658+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:14:43.681+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-11-16T15:15:13.842+0000] {processor.py:154} INFO - Started process (PID=1567) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:13.843+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:15:13.843+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:15:13.843+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:13.850+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:15:13.849+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:15:13.851+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:13.874+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:15:44.040+0000] {processor.py:154} INFO - Started process (PID=1590) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:44.041+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:15:44.041+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:15:44.041+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:44.048+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:15:44.047+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:15:44.049+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:15:44.071+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-11-16T15:16:14.222+0000] {processor.py:154} INFO - Started process (PID=1623) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:14.223+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:16:14.224+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:16:14.224+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:14.230+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:16:14.229+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:16:14.231+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:14.256+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-11-16T15:16:44.426+0000] {processor.py:154} INFO - Started process (PID=1645) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:44.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:16:44.428+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:16:44.427+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:44.434+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:16:44.433+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:16:44.435+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:16:44.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2022-11-16T15:17:14.623+0000] {processor.py:154} INFO - Started process (PID=1677) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:14.624+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:17:14.625+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:17:14.625+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:14.630+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:17:14.629+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:17:14.630+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:14.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2022-11-16T15:17:44.792+0000] {processor.py:154} INFO - Started process (PID=1700) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:44.794+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:17:44.795+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:17:44.794+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:44.801+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:17:44.800+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:17:44.802+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:17:44.822+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2022-11-16T15:18:14.977+0000] {processor.py:154} INFO - Started process (PID=1732) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:14.977+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:18:14.978+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:18:14.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:14.984+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:18:14.983+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:18:14.985+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:15.008+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2022-11-16T15:18:45.161+0000] {processor.py:154} INFO - Started process (PID=1756) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:45.161+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:18:45.162+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:18:45.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:45.169+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:18:45.168+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:18:45.169+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:18:45.193+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-11-16T15:19:15.346+0000] {processor.py:154} INFO - Started process (PID=1788) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:15.349+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:19:15.350+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:19:15.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:15.356+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:19:15.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:19:15.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:15.389+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2022-11-16T15:19:45.513+0000] {processor.py:154} INFO - Started process (PID=1817) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:45.515+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:19:45.516+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:19:45.516+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:45.524+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:19:45.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:19:45.525+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:19:45.554+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2022-11-16T15:20:10.695+0000] {processor.py:154} INFO - Started process (PID=1842) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:10.696+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:20:10.697+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:10.696+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:10.704+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:10.703+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-16T15:20:10.704+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:10.729+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2022-11-16T15:20:40.845+0000] {processor.py:154} INFO - Started process (PID=1865) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:40.846+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:20:40.847+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:40.847+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:40.907+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:20:41.270+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.270+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:my_first_dag
[2022-11-16T15:20:41.285+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.285+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:my_first_dag
[2022-11-16T15:20:41.296+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.296+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:my_first_dag
[2022-11-16T15:20:41.297+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.296+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:20:41.318+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.318+0000] {dag.py:2606} INFO - Creating ORM DAG for my_first_dag
[2022-11-16T15:20:41.341+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:20:41.341+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:20:41.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.530 seconds
[2022-11-16T15:21:11.556+0000] {processor.py:154} INFO - Started process (PID=1896) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:11.557+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:21:11.558+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:11.557+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:11.578+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:11.629+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:11.628+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:21:11.666+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:11.666+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:21:11.696+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.144 seconds
[2022-11-16T15:21:41.857+0000] {processor.py:154} INFO - Started process (PID=1922) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:41.857+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:21:41.858+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:41.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:41.882+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:21:41.930+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:41.930+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:21:41.964+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:21:41.964+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:21:41.988+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.135 seconds
[2022-11-16T15:22:12.024+0000] {processor.py:154} INFO - Started process (PID=1954) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:12.025+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:22:12.026+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:12.026+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:12.053+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:12.114+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:12.114+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:22:12.176+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:12.175+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:22:12.203+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.184 seconds
[2022-11-16T15:22:42.304+0000] {processor.py:154} INFO - Started process (PID=1975) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:42.305+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:22:42.306+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:42.306+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:42.325+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:22:42.371+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:42.371+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:22:42.404+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:22:42.404+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:22:42.430+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.130 seconds
[2022-11-16T15:23:12.557+0000] {processor.py:154} INFO - Started process (PID=2007) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:12.558+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:23:12.559+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:12.559+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:12.588+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:12.747+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:12.747+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:23:12.916+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:12.916+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:23:12.998+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.445 seconds
[2022-11-16T15:23:43.192+0000] {processor.py:154} INFO - Started process (PID=2030) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:43.193+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:23:43.194+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:43.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:43.228+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:23:43.303+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:43.303+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:23:43.359+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:23:43.359+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:23:43.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.235 seconds
[2022-11-16T15:24:13.587+0000] {processor.py:154} INFO - Started process (PID=2061) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:13.588+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:24:13.589+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:13.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:13.623+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:13.688+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:13.687+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:24:13.731+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:13.730+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:24:13.783+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.201 seconds
[2022-11-16T15:24:43.946+0000] {processor.py:154} INFO - Started process (PID=2084) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:43.947+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:24:43.948+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:43.947+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:43.967+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:44.037+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:44.037+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:24:44.077+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:44.076+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:24:44.101+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.159 seconds
[2022-11-16T15:24:58.020+0000] {processor.py:154} INFO - Started process (PID=2098) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:58.021+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:24:58.022+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:58.022+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:58.050+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:24:58.236+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:58.236+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:24:58.291+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:24:58.291+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:24:58.329+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.314 seconds
[2022-11-16T15:25:28.415+0000] {processor.py:154} INFO - Started process (PID=2130) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:28.416+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:25:28.417+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:25:28.417+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:28.437+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:28.501+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:25:28.500+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:25:28.594+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:25:28.594+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:25:28.631+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.220 seconds
[2022-11-16T15:25:39.756+0000] {processor.py:154} INFO - Started process (PID=2144) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:39.760+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:25:39.762+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:25:39.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:39.768+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:25:39.766+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 23
    task2 =
           ^
SyntaxError: invalid syntax
[2022-11-16T15:25:39.771+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:25:39.834+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.089 seconds
[2022-11-16T15:26:07.877+0000] {processor.py:154} INFO - Started process (PID=2167) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:07.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:26:07.879+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:07.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:07.899+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:08.078+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:08.078+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:26:08.128+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:08.128+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:26:08.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.288 seconds
[2022-11-16T15:26:15.047+0000] {processor.py:154} INFO - Started process (PID=2181) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:15.054+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:26:15.056+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:15.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:15.070+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:15.066+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 27
    task1.
         ^
SyntaxError: invalid syntax
[2022-11-16T15:26:15.071+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:15.116+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
[2022-11-16T15:26:27.125+0000] {processor.py:154} INFO - Started process (PID=2195) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:27.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:26:27.128+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:27.127+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:27.146+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:27.144+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 27, in <module>
    task1.set
AttributeError: 'BashOperator' object has no attribute 'set'
[2022-11-16T15:26:27.146+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:27.183+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2022-11-16T15:26:37.180+0000] {processor.py:154} INFO - Started process (PID=2200) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:37.181+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:26:37.182+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:37.182+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:37.205+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:26:37.239+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:37.239+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:26:37.280+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:26:37.280+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:26:37.321+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.145 seconds
[2022-11-16T15:27:04.394+0000] {processor.py:154} INFO - Started process (PID=2233) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:04.395+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:27:04.396+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.396+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:04.419+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:04.612+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.612+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:my_first_dag_v2
[2022-11-16T15:27:04.632+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.632+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:my_first_dag_v2
[2022-11-16T15:27:04.647+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.647+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:my_first_dag_v2
[2022-11-16T15:27:04.647+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.647+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:27:04.670+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.669+0000] {dag.py:2606} INFO - Creating ORM DAG for my_first_dag_v2
[2022-11-16T15:27:04.688+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:04.688+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:27:04.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.324 seconds
[2022-11-16T15:27:34.869+0000] {processor.py:154} INFO - Started process (PID=2254) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:34.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:27:34.871+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:34.871+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:34.898+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:27:34.980+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:34.980+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:27:35.037+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:27:35.037+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:27:35.081+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.216 seconds
[2022-11-16T15:28:05.297+0000] {processor.py:154} INFO - Started process (PID=2286) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:05.298+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:28:05.300+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:05.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:05.339+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:05.416+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:05.415+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:28:05.465+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:05.465+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:28:05.496+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.204 seconds
[2022-11-16T15:28:35.653+0000] {processor.py:154} INFO - Started process (PID=2310) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:35.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:28:35.655+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:35.655+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:35.680+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:28:35.731+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:35.731+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:28:35.764+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:28:35.764+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:28:35.788+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.138 seconds
[2022-11-16T15:29:05.825+0000] {processor.py:154} INFO - Started process (PID=2342) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:05.826+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:29:05.828+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:05.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:05.856+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:05.912+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:05.912+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:29:05.964+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:05.964+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:29:06.005+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.186 seconds
[2022-11-16T15:29:14.005+0000] {processor.py:154} INFO - Started process (PID=2347) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:14.006+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:29:14.007+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:14.007+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:14.059+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:14.274+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:14.274+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:29:14.343+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:14.342+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:29:14.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.389 seconds
[2022-11-16T15:29:41.549+0000] {processor.py:154} INFO - Started process (PID=2381) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:41.558+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:29:41.559+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:41.559+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:41.582+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:41.618+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:41.617+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:29:41.671+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:41.671+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:29:41.729+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.185 seconds
[2022-11-16T15:29:56.625+0000] {processor.py:154} INFO - Started process (PID=2395) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:56.626+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:29:56.626+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:56.626+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:56.646+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v2']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:29:56.867+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:56.866+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:29:56.954+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:29:56.954+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v2 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:29:57.003+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.381 seconds
[2022-11-16T15:30:11.098+0000] {processor.py:154} INFO - Started process (PID=2409) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:11.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:30:11.100+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.100+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:11.135+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:11.363+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.363+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:my_first_dag_v3
[2022-11-16T15:30:11.381+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.381+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:my_first_dag_v3
[2022-11-16T15:30:11.393+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.393+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:my_first_dag_v3
[2022-11-16T15:30:11.394+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.394+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:30:11.416+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.416+0000] {dag.py:2606} INFO - Creating ORM DAG for my_first_dag_v3
[2022-11-16T15:30:11.447+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:11.447+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:30:11.483+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.391 seconds
[2022-11-16T15:30:41.716+0000] {processor.py:154} INFO - Started process (PID=2430) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:41.721+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:30:41.722+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:41.722+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:41.793+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:30:41.886+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:41.886+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:30:41.930+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:30:41.930+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:30:41.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.262 seconds
[2022-11-16T15:31:12.128+0000] {processor.py:154} INFO - Started process (PID=2462) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:12.129+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:31:12.129+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:12.129+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:12.153+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:12.208+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:12.208+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:31:12.253+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:12.253+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:31:12.280+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.156 seconds
[2022-11-16T15:31:42.342+0000] {processor.py:154} INFO - Started process (PID=2485) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:42.342+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:31:42.343+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:42.343+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:42.364+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:31:42.414+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:42.414+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:31:42.451+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:31:42.451+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:31:42.480+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.142 seconds
[2022-11-16T15:32:12.650+0000] {processor.py:154} INFO - Started process (PID=2517) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:12.651+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:32:12.652+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:12.651+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:12.672+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:12.721+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:12.721+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:32:12.755+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:12.755+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:32:12.779+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.134 seconds
[2022-11-16T15:32:42.821+0000] {processor.py:154} INFO - Started process (PID=2541) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:42.823+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:32:42.825+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:42.824+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:42.860+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:32:42.952+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:42.952+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:32:43.008+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:32:43.008+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:32:43.045+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.229 seconds
[2022-11-16T15:33:13.098+0000] {processor.py:154} INFO - Started process (PID=2572) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:13.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:33:13.099+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:13.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:13.123+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:13.179+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:13.179+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:33:13.222+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:13.221+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:33:13.246+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.153 seconds
[2022-11-16T15:33:43.391+0000] {processor.py:154} INFO - Started process (PID=2595) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:43.393+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:33:43.395+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:43.394+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:43.425+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:33:43.510+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:43.510+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:33:43.571+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:33:43.571+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:33:43.609+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.221 seconds
[2022-11-16T15:34:13.779+0000] {processor.py:154} INFO - Started process (PID=2626) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:13.780+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:34:13.781+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:13.781+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:13.817+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:13.926+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:13.925+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:34:13.993+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:13.991+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:34:14.035+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.261 seconds
[2022-11-16T15:34:44.201+0000] {processor.py:154} INFO - Started process (PID=2649) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:44.202+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:34:44.203+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:44.203+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:44.227+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:34:44.305+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:44.304+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:34:44.368+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:34:44.368+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:34:44.401+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.205 seconds
[2022-11-16T15:35:14.567+0000] {processor.py:154} INFO - Started process (PID=2682) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:14.568+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:35:14.569+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:14.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:14.589+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:14.648+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:14.648+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:35:14.691+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:14.691+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:35:14.721+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.159 seconds
[2022-11-16T15:35:44.879+0000] {processor.py:154} INFO - Started process (PID=2705) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:44.880+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:35:44.881+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:44.881+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:44.908+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:35:44.971+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:44.971+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:35:45.009+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:35:45.009+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:35:45.037+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.163 seconds
[2022-11-16T15:36:15.599+0000] {processor.py:154} INFO - Started process (PID=2763) to work on /opt/airflow/dags/first_dag.py
[2022-11-16T15:36:15.603+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-11-16T15:36:15.605+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:36:15.604+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-11-16T15:36:15.663+0000] {processor.py:766} INFO - DAG(s) dict_keys(['my_first_dag_v3']) retrieved from /opt/airflow/dags/first_dag.py
[2022-11-16T15:36:15.765+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:36:15.765+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-16T15:36:15.842+0000] {logging_mixin.py:137} INFO - [2022-11-16T15:36:15.841+0000] {dag.py:3340} INFO - Setting next_dagrun for my_first_dag_v3 to 2022-11-17T00:00:00+00:00, run_after=2022-11-18T00:00:00+00:00
[2022-11-16T15:36:15.889+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/first_dag.py took 0.304 seconds
